#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* http://127.0.0.1:3000/docs/myoptions-generator-new.html?r=72,2,11,36,42,44,48&i=1,2,3,4,18,19,20,21&v=255,255,-1,255,40,16,8,-1 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ST7735
#define DSP_HSPI			true
#define I2S_DOUT			255
#define VS_HSPI			true
#define VS1053_CS			40
#define VS1053_DCS			16
#define VS1053_DREQ			8


#endif
